#数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 858937
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.huang.xml.model
  configuration:
    cache-enabled: true # 该配置影响的所有映射器中配置的缓存的全局开关。 默认true
    lazy-loading-enabled: false #  延迟加载的全局开关。当开启时，所有关联对象都会延迟加载。 特定关联关系中可通过设置fetchType属性来覆盖该项的开关状态。 false
    aggressive-lazy-loading: true  # 当启用时，对任意延迟属性的调用会使带有延迟加载属性的对象完整加载；反之，每种属性将会按需加载。
    multiple-result-sets-enabled: true # 是否允许单一语句返回多结果集（需要兼容驱动）。
    use-column-label: true # 使用列标签代替列名。不同的驱动在这方面会有不同的表现， 具体可参考相关驱动文档或通过测试这两种不同的模式来观察所用驱动的结果。
    use-generated-keys: false # 允许 JDBC 支持自动生成主键，需要驱动兼容。 如果设置为 true 则这个设置强制使用自动生成主键，尽管一些驱动不能兼容但仍可正常工作（比如 Derby）。
    auto-mapping-behavior: partial # 指定 MyBatis 应如何自动映射列到字段或属性。 NONE 表示取消自动映射；PARTIAL 只会自动映射没有定义嵌套结果集映射的结果集。 FULL 会自动映射任意复杂的结果集（无论是否嵌套）。
    default-executor-type: simple
    default-statement-timeout: 25
    safe-row-bounds-enabled: false
    map-underscore-to-camel-case: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: